server: 
  port: 8081

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # 테이블 자동갱신
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html

openapi:
  info:
    title: Leafy API Documentation
    version: 1.0.0
    description: API documentation for the Leafy application.