server: 
  port: 8081

spring:
  # --- 1. 데이터베이스 및 JPA 설정 (PostgreSQL 환경 변수 기반) ---
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # 테이블 자동갱신
    properties:
      hibernate:
        format_sql: true
    show_sql: true

  # --- 2. H2 콘솔 설정 (개발용) ---
  h2:
    console:
      enabled: true
      path: /h2-console
# --- 3. Spring Security OAuth2 Client 설정 (카카오 로그인) ---
  security:
    oauth2:
      client:
        registration:
          kakao: # 'kakao'는 registrationId
            client-id: 026700dcec278b7ea3e9941b3c47ca75
            client-secret: wVitZH9LR7em2JtQ1AfGbqSf6XxvE436
            # {baseUrl}은 Spring이 자동으로 채워주므로 환경 변화에 유연함
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            # 카카오 인증 서버에서 사용자 식별자로 사용되는 속성 (PK)
            user-name-attribute: id
springdoc:
  swagger-ui:
    path: /swagger-ui.html

openapi:
  info:
    title: Leafy API Documentation
    version: 1.0.0
    description: API documentation for the Leafy application.